# Generated by Django 5.2.7 on 2026-03-11 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_remove_servicecategory_base_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
