# Generated by Django 5.2.7 on 2026-03-11 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_booking_service_type_booking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='diagnostic_report',
            field=models.TextField(blank=True, help_text='Detailed diagnostic report provided by the mechanic.', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReplacedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('part_photo', models.ImageField(blank=True, null=True, upload_to='parts_photos/')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaced_parts', to='services.booking')),
            ],
        ),
    ]
