# Generated by Django 5.2.7 on 2026-03-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_booking_diagnostic_report_alter_booking_service_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceBooking',
        ),
    ]
